apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-test-chart.fullname" . }}-config
  labels:
    {{- include "my-test-chart.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.appConfig.logLevel | quote }}
  externalUrl: {{ .Values.appConfig.externalUrl | quote }}
  # Exemplo de conteúdo de configuração para Nginx
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
  # Exemplo usando loop e condicionais
  features.json: |
    {
      {{- range $key, $val := .Values.appConfig.featureFlags }}
      "{{ $key }}": {{ $val | toJson }}{{ if not (last $key $.Values.appConfig.featureFlags) }},{{ end }}
      {{- end }}
    }