apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-test-chart.fullname" . }}
  labels:
    {{- include "my-test-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-test-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-test-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf # Exemplo
              subPath: nginx.conf # Mapeia uma chave específica do ConfigMap
            - name: secret-volume
              mountPath: /etc/secret-data
              readOnly: true
        {{- if .Values.sidecarContainer.enabled }}
        - name: {{ .Values.sidecarContainer.name }}
          image: "{{ .Values.sidecarContainer.image.repository }}:{{ .Values.sidecarContainer.image.tag }}"
          imagePullPolicy: {{ .Values.sidecarContainer.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.sidecarContainer.securityContext | nindent 12 }}
          ports:
          {{- range .Values.sidecarContainer.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
          {{- end }}
          resources:
            {{- toYaml .Values.sidecarContainer.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "my-test-chart.fullname" . }}-config
        - name: secret-volume
          secret:
            secretName: {{ include "my-test-chart.fullname" . }}-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}