apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-test-chart.fullname" . }}-secret
  labels:
    {{- include "my-test-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "my-test-chart.secretData" . | nindent 2 }}